//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHOTSOLIEU
    {
        public int ID { get; set; }
        public string DV { get; set; }
        public string SOHD { get; set; }
        public string LGTHANG { get; set; }
        public Nullable<double> TONGBH { get; set; }
        public Nullable<double> TONGTHUE { get; set; }
        public Nullable<double> CDP { get; set; }
        public Nullable<double> DNVHG { get; set; }
        public Nullable<double> DVP { get; set; }
        public Nullable<double> TONGTIENDN { get; set; }
        public string NGUOISD { get; set; }
        public Nullable<System.DateTime> NGAYIN { get; set; }
        public Nullable<bool> tinhtrang { get; set; }
        public string MANHOMFC { get; set; }
        public Nullable<bool> DACHOT { get; set; }
        public Nullable<System.DateTime> NGAYGIOCHOT { get; set; }
        public string NGUOICHOT { get; set; }
        public string Ghichu { get; set; }
        public string NGUOIYC_HUY { get; set; }
        public Nullable<System.DateTime> NGAYYC_HUY { get; set; }
        public string SCAN { get; set; }
        public string Note { get; set; }
        public Nullable<double> CDP138 { get; set; }
        public string LOAIGB { get; set; }
        public Nullable<bool> CHOTTIENVE { get; set; }
        public Nullable<System.DateTime> NGAYCHOTTIENVE { get; set; }
        public string NGUOICHOTTIENVE { get; set; }
        public Nullable<double> TONGBHTN { get; set; }
        public Nullable<int> SttDitien { get; set; }
        public string GhichuDitien { get; set; }
        public Nullable<System.DateTime> NgayDiTien { get; set; }
    }
}
