//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONGNO
    {
        public int ID { get; set; }
        public string MADV { get; set; }
        public Nullable<System.DateTime> NGAYCN { get; set; }
        public Nullable<double> DATRA { get; set; }
        public Nullable<double> CONLAI { get; set; }
        public string GHICHU { get; set; }
        public string NGUOISD { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public Nullable<System.DateTime> NGAYSUA { get; set; }
        public Nullable<bool> TRANGTHAI { get; set; }
        public string TENDV { get; set; }
        public string DIACHI { get; set; }
        public string NGUOITAO { get; set; }
    }
}
