//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTNH
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> NGAYGIAODICH { get; set; }
        public string SOTHAMCHIEU { get; set; }
        public string MADV { get; set; }
        public Nullable<double> SOTIENCO { get; set; }
        public string MOTA { get; set; }
        public string GHICHU { get; set; }
    }
}
