//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonVi
    {
        public int ID_DonVi { get; set; }
        public string MaDonVi { get; set; }
        public string TenDonVi { get; set; }
        public string TrangThai { get; set; }
        public Nullable<System.DateTime> NgayThanhLap { get; set; }
        public string TenNhomFosco { get; set; }
        public string QuocTich { get; set; }
        public string DienThoaiDonVi { get; set; }
        public string EmailDonVi { get; set; }
        public string EmailLienHe { get; set; }
        public string DiaChiDonVi { get; set; }
        public string SoNhaDuongDonVi { get; set; }
        public string TinhThanhPhoDonVi { get; set; }
        public string QuanHuyenDonVi { get; set; }
        public string PhuongXaDonVi { get; set; }
        public string SoTaiKhoan { get; set; }
        public string NganHang { get; set; }
        public string ChiNhanhNganHang { get; set; }
        public string MaSoThue { get; set; }
        public string NgayCapMaSoThue { get; set; }
        public string MaBHXH { get; set; }
        public string MaBHXH_NN { get; set; }
        public string NgayNghiHangTuan { get; set; }
        public string LoaiLuong { get; set; }
        public string GiayPhepDonVi { get; set; }
        public string NgayCapGiayPhepDonVi { get; set; }
        public string CoQuanCapGiayPhepDonVi { get; set; }
        public string DichVuPhi { get; set; }
        public string HoTenNguoiLienHeKhanCap { get; set; }
        public string QuanHeLienHeKhanCap { get; set; }
        public string DienThoaiDiDongLienHeKhanCap { get; set; }
        public string EmailLienHeKhanCap { get; set; }
        public string DiaChiLienHeKhanCap { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> NgayKyHopDong { get; set; }
        public Nullable<System.DateTime> NgayKetThucHopDong { get; set; }
        public string LoaiDonVi { get; set; }
        public Nullable<System.DateTime> NGAY_VAO { get; set; }
        public Nullable<int> KINHPHICD { get; set; }
        public string NoiNopThue { get; set; }
        public string NganHangNopThue { get; set; }
        public string SoTaiKhoanNopThue { get; set; }
    }
}
