//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSNV
    {
        public string MANVQL { get; set; }
        public string HODEM { get; set; }
        public string TEN { get; set; }
        public string MATKHAU { get; set; }
        public string MANHOM { get; set; }
        public string GHICHU { get; set; }
        public Nullable<int> LOGIN { get; set; }
        public Nullable<int> KHOATAIKHOAN { get; set; }
        public Nullable<int> Khoasolieu { get; set; }
        public Nullable<int> Chinhsua { get; set; }
        public Nullable<int> InSL { get; set; }
        public Nullable<int> Xem { get; set; }
        public Nullable<System.DateTime> login_date { get; set; }
        public string NHOMSD { get; set; }
        public Nullable<int> xemCN { get; set; }
        public string SOCMND { get; set; }
        public string NOICAP { get; set; }
        public string NGAYCAP { get; set; }
    }
}
