//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHANQUYEN
    {
        public int ID { get; set; }
        public Nullable<int> ID_CHUCNANG { get; set; }
        public Nullable<bool> TOANQUYEN { get; set; }
        public Nullable<bool> XEM { get; set; }
        public Nullable<bool> XOA { get; set; }
        public Nullable<bool> SUA { get; set; }
        public Nullable<bool> THEM { get; set; }
        public string IDUSER { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public Nullable<System.DateTime> NGAYSUA { get; set; }
    }
}
