//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Q_HSC
    {
        public string MADV { get; set; }
        public string MABHXH { get; set; }
        public string MaSoBHXH { get; set; }
        public string MANV { get; set; }
        public string HOTEN { get; set; }
        public string HODEM { get; set; }
        public string TEN { get; set; }
        public string GT { get; set; }
        public string NGAYVAO { get; set; }
        public string DIACHI { get; set; }
        public string DTDD { get; set; }
        public string EMAIL { get; set; }
        public string CONGVIEC { get; set; }
        public string SoCMND { get; set; }
        public string NGAYCAPCMND { get; set; }
        public string NoiCapCMND { get; set; }
        public string SoCCCD { get; set; }
        public string NGAYCAPCCCD { get; set; }
        public string NoiCapCCCD { get; set; }
        public string DanToc { get; set; }
        public string TonGiao { get; set; }
        public string QT { get; set; }
        public string MST { get; set; }
        public string SOTK { get; set; }
        public string NganHang { get; set; }
        public string TINHTP { get; set; }
        public string TRINHDO { get; set; }
        public string LOAILG { get; set; }
        public string DVP { get; set; }
        public string NHOMFC { get; set; }
        public Nullable<double> LTLD { get; set; }
        public Nullable<double> LCV_HSC { get; set; }
        public string DVT { get; set; }
        public string DONVICONGTAC { get; set; }
        public Nullable<double> TIENPC { get; set; }
        public Nullable<double> AN { get; set; }
        public Nullable<double> DT { get; set; }
        public Nullable<double> CT { get; set; }
        public Nullable<double> TP { get; set; }
        public Nullable<double> KHAC { get; set; }
        public Nullable<double> PC_TIENNHA { get; set; }
        public string HD_Nha { get; set; }
        public Nullable<double> KHAC_KTHUE { get; set; }
        public string DVTPC { get; set; }
        public Nullable<int> SOPT { get; set; }
        public string CD { get; set; }
        public string LOAINV { get; set; }
        public Nullable<System.DateTime> NGAYNGHIVIEC { get; set; }
        public string L_HDLD { get; set; }
        public string TenTrangthaiLamViec { get; set; }
        public int Trangthai { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
    }
}
