//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DSNV> DSNVs { get; set; }
        public virtual DbSet<T_THUENN> T_THUENN { get; set; }
        public virtual DbSet<TBL_Option> TBL_Option { get; set; }
        public virtual DbSet<TIGIA> TIGIAs { get; set; }
        public virtual DbSet<Q_HSC> Q_HSC { get; set; }
        public virtual DbSet<T_TIENMAT> T_TIENMAT { get; set; }
        public virtual DbSet<DonVi> DonVis { get; set; }
        public virtual DbSet<CONGNO> CONGNOes { get; set; }
        public virtual DbSet<CHUCNANG> CHUCNANGs { get; set; }
        public virtual DbSet<PHANQUYEN> PHANQUYENs { get; set; }
        public virtual DbSet<CHOTSOLIEU> CHOTSOLIEUx { get; set; }
        public virtual DbSet<ThietBi> ThietBis { get; set; }
        public virtual DbSet<CTNH> CTNHs { get; set; }
    
        public virtual int NgayHienHanh()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NgayHienHanh");
        }
    }
}
