//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_THUENN
    {
        public int Id { get; set; }
        public string LGTHANG { get; set; }
        public string MADV { get; set; }
        public string MANV { get; set; }
        public string HODEM { get; set; }
        public string TEN { get; set; }
        public Nullable<double> LCV_USD { get; set; }
        public Nullable<double> DLCV { get; set; }
        public Nullable<double> PHUCAP { get; set; }
        public Nullable<double> THUONG { get; set; }
        public Nullable<double> KHAC { get; set; }
        public Nullable<double> TIENNHA { get; set; }
        public Nullable<double> LGTNCN { get; set; }
        public Nullable<double> GT_BANTHAN { get; set; }
        public Nullable<double> GT_PHUTHUOC { get; set; }
        public Nullable<double> TNCN { get; set; }
        public Nullable<double> TTN { get; set; }
        public Nullable<double> NVBHXH { get; set; }
        public Nullable<double> PDV { get; set; }
        public Nullable<double> DNVHG { get; set; }
        public Nullable<double> TONGTIEN_DN { get; set; }
        public string SOHD { get; set; }
        public string NGAYHD { get; set; }
        public string SOGNT { get; set; }
        public string DIENGIAI { get; set; }
        public string DISCRIPTION { get; set; }
        public string KYTHUE { get; set; }
        public Nullable<double> SOTIENVE { get; set; }
        public string NGAYTIENVE { get; set; }
        public string PHANTICH { get; set; }
        public string SOBIENLAI { get; set; }
        public string NGAYTC { get; set; }
        public string NGAYBL { get; set; }
        public string NGAYNOPTHUE { get; set; }
        public Nullable<double> TIEN_VN { get; set; }
        public Nullable<double> THUA { get; set; }
        public string XLTHUA { get; set; }
        public Nullable<double> THIEU { get; set; }
        public string XLTHIEU { get; set; }
        public string GHICHU { get; set; }
        public string NGUOISD { get; set; }
        public Nullable<double> TGLG { get; set; }
        public Nullable<double> TGBHXH { get; set; }
        public string NGAYTAO { get; set; }
        public string TIENCHU { get; set; }
    }
}
