//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TIENMAT
    {
        public int ID { get; set; }
        public string MADV { get; set; }
        public string TENDV { get; set; }
        public string NOIDUNGTRA { get; set; }
        public string NGAYTRA { get; set; }
        public string SOHD { get; set; }
        public string THANGCN { get; set; }
        public Nullable<double> BHXH_YT { get; set; }
        public Nullable<double> BHTN { get; set; }
        public Nullable<double> TTN { get; set; }
        public Nullable<double> DVP { get; set; }
        public Nullable<int> PHIEUTHU { get; set; }
        public Nullable<double> T_LUONG { get; set; }
        public Nullable<int> HTHUC { get; set; }
        public Nullable<double> LUONG { get; set; }
        public Nullable<double> CDP { get; set; }
        public string NGUOISD { get; set; }
    }
}
