//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThietBi
    {
        public int ID { get; set; }
        public string MaThietBi { get; set; }
        public string LoaiThietBi { get; set; }
        public string TenThietBi { get; set; }
        public Nullable<System.DateTime> NgayMua { get; set; }
        public Nullable<System.DateTime> NgayThanhLy { get; set; }
        public Nullable<System.DateTime> NgaySuDung { get; set; }
        public Nullable<int> ID_Nhatky { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string NhomThietBi { get; set; }
        public string NguoiSuDung { get; set; }
        public string GhiChu { get; set; }
        public string Tinhtrang { get; set; }
        public Nullable<bool> Enable { get; set; }
        public Nullable<System.DateTime> NgayKiemKe { get; set; }
        public Nullable<double> DONGIA { get; set; }
    }
}
