//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIGIA
    {
        public int ID { get; set; }
        public string THANGNAM { get; set; }
        public double TGLG { get; set; }
        public double TGBHXH { get; set; }
        public string GHICHU { get; set; }
    }
}
